name: 05 - Reusable Build

on:
  workflow_call:
    inputs:
      message:
        type: string
        default: 'Hello from reusable workflow'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.message }}"
